name: Run unit tests

on: [push]

jobs:
  run-unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        name: Install bun
        with:
          bun-version: 1.0.11

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "bun"

      - name: Install dependencies
        run: bun install

      - name: Run unit tests
        run: bun test
